env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:vue/essential
  - '@vue/typescript/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
